export const SHOW_OR_HIDE_HEADER = "SHOW_OR_HIDE_HEADER";
export const SHOW_OR_HIDE_FOOTER = "SHOW_OR_HIDE_FOOTER";
export const SHOW_OR_HIDE_COMMONPAGE = 'SHOW_OR_HIDE_COMMONPAGE'
export const HEADER_CONFIG = "HEADER_CONFIG";
export const SHOW_OR_HIDE_SEARCH = "SHOW_OR_HIDE_SEARCH";
export const SHOW_OR_HIDE_SEARCH_DIALOG = 'SHOW_OR_HIDE_SEARCH_DIALOG'
export const INIT_PAGE_CONFIG = "INIT_PAGE_CONFIG"